name: app_name_package
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.18
  url_launcher: ^6.1.10
  dio: ^5.0.3
  intl: ^0.18.0
  cached_network_image: ^3.2.3
  google_sign_in: ^6.0.2
  flutter_dotenv: ^5.0.2
  logger: ^1.3.0
  permission_handler: ^10.2.0
  uni_links: ^0.5.1
  share_plus: ^6.3.1
  oktoast: ^3.3.1
  timeago: ^3.4.0
  get: ^4.6.5
  firebase_dynamic_links: ^5.0.17
  flutter_screenutil: ^5.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
